from functions.processing import generate_table

generate_table("emissions_profile_upstream_products_raw")
generate_table("emissions_profile_any_companies_raw")
generate_table("emissions_profile_any_companies_ecoinvent_raw")
generate_table("sector_profile_upstream_companies_raw")
generate_table("sector_profile_upstream_products_raw")
generate_table("emissions_profile_upstream_products_ecoinvent_raw")
generate_table("emissions_profile_products_raw")
generate_table("emissions_profile_products_ecoinvent_raw")
generate_table("sector_profile_companies_raw") 
generate_table("sector_profile_any_scenarios_raw")
